2013-08-15 14:28:44 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): www.cefconnect.com
2013-08-15 15:04:19 - scrape.scrape_tickers - INFO - ticker_list update: FSFR

2013-08-15 15:04:19 - scrape.scrape_tickers - INFO - ticker_list update: KIO

2013-08-15 15:04:38 - scrape.scrape_info - ERROR - Rank 2: Ticker ACAS
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:04:49 - scrape.scrape_info - ERROR - Rank 0: Ticker ARCC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:04:51 - scrape.scrape_info - ERROR - Rank 1: Ticker AINV
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:05:07 - scrape.scrape_info - ERROR - Rank 2: Ticker BKCC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:05:48 - scrape.scrape_info - ERROR - Rank 2: Ticker CSWC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:06:10 - scrape.scrape_info - ERROR - Rank 1: Ticker CORR
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:06:51 - scrape.scrape_info - ERROR - Rank 2: Ticker EQS
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:06:56 - scrape.scrape_info - ERROR - Rank 2: Ticker FDUS
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:06 - scrape.scrape_info - ERROR - Rank 1: Ticker SVVC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:10 - scrape.scrape_info - ERROR - Rank 3: Ticker ETUB
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:15 - scrape.scrape_info - ERROR - Rank 3: Ticker FSC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:18 - scrape.scrape_info - ERROR - Rank 0: Ticker GARS
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:18 - scrape.scrape_info - ERROR - Rank 1: Ticker FULL
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:20 - scrape.scrape_info - ERROR - Rank 2: Ticker GBDC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:21 - scrape.scrape_info - ERROR - Rank 0: Ticker GAIN
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:24 - scrape.scrape_info - ERROR - Rank 0: Ticker GSVC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:25 - scrape.scrape_info - ERROR - Rank 2: Ticker TINY
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:32 - scrape.scrape_info - ERROR - Rank 3: Ticker GLUXR
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:38 - scrape.scrape_info - ERROR - Rank 3: Ticker GLAD
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:38 - scrape.scrape_info - ERROR - Rank 1: Ticker HTGC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:45 - scrape.scrape_info - ERROR - Rank 3: Ticker HCAP
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:07:49 - scrape.scrape_info - ERROR - Rank 3: Ticker HRZN
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:01 - scrape.scrape_info - ERROR - Rank 2: Ticker KIPO
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:11 - scrape.scrape_info - ERROR - Rank 1: Ticker KCAP
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:15 - scrape.scrape_info - ERROR - Rank 0: Ticker TAXI
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:25 - scrape.scrape_info - ERROR - Rank 1: Ticker MCC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:35 - scrape.scrape_info - ERROR - Rank 1: Ticker MRCC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:38 - scrape.scrape_info - ERROR - Rank 0: Ticker NGPC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:39 - scrape.scrape_info - ERROR - Rank 2: Ticker NMFC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:39 - scrape.scrape_info - ERROR - Rank 3: Ticker MAIN
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:42 - scrape.scrape_info - ERROR - Rank 3: Ticker MCGC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:08:59 - scrape.scrape_info - ERROR - Rank 3: Ticker MVC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:09:22 - scrape.scrape_info - ERROR - Rank 1: Ticker NMD
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:09:52 - scrape.scrape_info - ERROR - Rank 2: Ticker PNNT
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:09:58 - scrape.scrape_info - ERROR - Rank 1: Ticker OFS
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:01 - scrape.scrape_info - ERROR - Rank 0: Ticker PSEC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:01 - scrape.scrape_info - ERROR - Rank 1: Ticker PFLT
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:08 - scrape.scrape_info - ERROR - Rank 0: Ticker RAND
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:20 - scrape.scrape_info - ERROR - Rank 0: Ticker SUNS
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:23 - scrape.scrape_info - ERROR - Rank 2: Ticker SCM
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:27 - scrape.scrape_info - ERROR - Rank 1: Ticker SAR
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:31 - scrape.scrape_info - ERROR - Rank 0: Ticker TCPC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:34 - scrape.scrape_info - ERROR - Rank 2: Ticker TICC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:44 - scrape.scrape_info - ERROR - Rank 3: Ticker SLRC
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:10:45 - scrape.scrape_info - ERROR - Rank 1: Ticker TCRD
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:11:02 - scrape.scrape_info - ERROR - Rank 0: Ticker WHF
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:11:05 - scrape.scrape_info - ERROR - Rank 2: Ticker FSFR
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:11:08 - scrape.scrape_info - ERROR - Rank 3: Ticker TCAP
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:11:15 - scrape.scrape_info - ERROR - Rank 3: Ticker HIF
Traceback (most recent call last):
  File "pycef/lib/scrape/scrape_cefs.py", line 189, in scrape_info
    date = datetime.date(int(date[2]), int(date[0]), int(date[1]))
IndexError: list index out of range
2013-08-15 15:11:27 - scrape.scrape_cefs.CEFInfo - INFO - get_info: Unable to get info from ['ARCC', 'BTT', 'SZC', 'DMB', 'ETX', 'GARS', 'GAIN', 'GSVC', 'TAXI', 'NML', 'NGPC', 'NID', 'PSEC', 'RAND', 'SUNS', 'SPPP', 'EDI', 'TCPC', 'WHF', 'DFP', 'JPW']
2013-08-15 15:11:27 - scrape.scrape_cefs.CEFInfo - INFO - get_info: Unable to get info from ['AINV', 'ARDC', 'BIT', 'CORR', 'SVVC', 'FEI', 'FULL', 'HTGC', 'KCAP', 'MCC', 'MRCC', 'NIQ', 'NMD', 'OFS', 'PFLT', 'PCI', 'GHY', 'SAR', 'TCRD', 'IVH', 'PGZ']
2013-08-15 15:11:27 - scrape.scrape_cefs.CEFInfo - INFO - get_info: Unable to get info from ['ACAS', 'BKCC', 'CSWC', 'EQS', 'FDUS', 'GBDC', 'TINY', 'KIPO', 'NMFC', 'NXZ', 'PNNT', 'SCM', 'TICC', 'CBA', 'FSFR']
2013-08-15 15:11:27 - scrape.scrape_cefs.CEFInfo - INFO - get_info: Unable to get info from ['AIF', 'BGH', 'BUI', 'BGB', 'BOI', 'MIE', 'DSL', 'ETUB', 'FSC', 'GLUXR', 'GLAD', 'HCAP', 'HRZN', 'MAIN', 'MCGC', 'MVC', 'SLRC', 'TCAP', 'HIF', 'FPF', 'EFF', 'KIO']
2013-08-15 15:11:27 - scrape - WARNING - self.cef_get.get_info() failed
